apiVersion: v1
kind: ConfigMap
metadata:
  name: common-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  OTEL_EXPORTER_OTLP_ENDPOINT: http://aspire-dashboard:18889
  OTEL_EXPORTER_OTLP_PROTOCOL: grpc
  Kafka__BootstrapServers: kafka:9092
